### ISSUE TITLE
Does the weight/BMI/sex regression meet validity criterion?

### ISSUE THREAD

**Issue by alanocallaghan** [carpentries-incubator/multiple-linear-regression-public-health#15]
From the previous lesson:

> B) Does the model include all relevant explanatory variables? 

Since BMI is weight/height^2, it seems odd to include only one. Perhaps there's another predictor other than weight that could be used? Otherwise would be perhaps good to ask about it, or to mention it as a gotcha

**Comment by ezherman** [comment]
Hey @Alanocallaghan, that's a good question! I agree that height would be a sensible inclusion here, however then I am think the model would fit the data perfectly (since the BMI was probably calculated from the weight and height columns). 

I like the idea of having a different predictor than weight, but I don't remember finding an association that is as neat as BMI ~ Weight + Sex. It's not a relevant model for the real world, but I think it demonstrates the ideal scenario for inclusion of a categorical variable without an interaction. 

I will leave this issue open, as I or someone else can perhaps look for a more relevant example in the NHANES data at another time.

**Comment by alanocallaghan** [comment]
It is a nice example, especially as it allows you to explore why the effect is different between sexes (bimodal height distribution). If I find time I may add a callout box explaining this
