### ISSUE TITLE
Assessing multiple linear regression model fit and assumptions

### ISSUE THREAD

**Issue by 3mmaRand** [carpentries-incubator/multiple-linear-regression-public-health#9]
Assessing multiple linear regression model fit and assumptions

https://carpentries-incubator.github.io/multiple-linear-regression-public-health/04-assumptionsAndFit/index.html

adding explanatory variables to our model will almost always increase R2,
->
maybe: adding explanatory variables to our model will always increase R2,

Link to episode 2 in the Exercise is broken.

In episode 2 we used the default digits = 2 in summ(). Consider changing that to 3? Or droping digits = 3 here.

The R^2 is still the proportion of variance explained by the model as is; the adjusted R^2 is the proportion variance explained by the variables that matter in the model

Recall out child_logWeight_Height_lm model 
->
Recall **our** child_logWeight_Height_lm model 

Equal variance of errors (homoscedasticity) section:
- since people would probably run the code in the Hemoglobin_Age_Sex example, maybe include loading patchwork

Key points:
The variable needs increase model fit for the adjusted R squared to increase.
->
The variable needs improve model fit for the adjusted R squared to increase.

_When you take a look at the homoscedasticity challenge, could you comment on the unequal variance across sex? My guess is that this is problematic, however I'm suddenly doubting myself: I don't have an explanation for why unequal variance across a categorical variable would result inefficient estimation of the standard error of the parameter estimate for the dummy variable. No worries if you're not sure either, I can try to dig into this at some point ahead of the workshop!_

ummm, my feeling was that it is not problematic for the parameter estimation but that it did matter for any hypothesis testing. You've probably seen wikipedia which says (unreferenced) that homoscedasticity is needed for unbaised s.e. This seems to be an explantion: https://econ.lse.ac.uk/staff/spischke/mhe/josh/Notes%20on%20conv%20std%20error.pdf (linked from http://www.mostlyharmlesseconometrics.com/2010/12/heteroskedasticity-and-standard-errors-big-and-small/#:~:text=Basically%2C%20conven

**Comment by ezherman** [comment]
Hi @3mmaRand, thanks for these comments! Those pages on heteroscedasticity were useful. You are right, the issue lies in pooling the residuals across the model to estimate the standard errors. This can result in over/underestimation of standard errors under heteroscedasticity. 

Does the following comment relate to the text on R^2 adjusted in the solution to the exercise? "_The R^2 is still the proportion of variance explained by the model as is; the adjusted R^2 is the proportion variance explained by the variables that matter in the model_"

As for including patchwork in the code, that will be covered already if students follow the setup page. But I will mention that the `+` comes from patchwork in the text.

**Comment by 3mmaRand** [comment]
hi @ezherman 

Yes, that's what I meant. I initially felt we should say R^2 rather than R^2 adjusted in the solution. But I think I have changed my mind. Stick with what you wrote.

Gotcha on patchwork - though the Set up page on https://carpentries-incubator.github.io/multiple-linear-regression-public-health/setup.html doesn't have patchwork. The one for Simple linear reg does.

**Comment by ezherman** [comment]
Sounds good, I'll leave it as is then!

And well spotted - I will add patchwork now.
